#!/bin/bash

function print_histogram() {
    for n in "$@"
    do
        printf "%${n}s\n" '' | tr ' ' 'X'
    done
}

function unique_values_desc() {
    # Unique values sorted in descending order
    printf '%s\n' "$@" | sort -rg | uniq
}

function truncate_lines_to() {
    local max_width=$1
    cut -c "1-${max_width}"
}

function largest_full_rect() {
    uniq -c | awk '{ print $1 * length($2) }' | sort -gr | head -n 1
}

function largest_rect_in_histogram() {
    local histogram=$(print_histogram "$@")
    local maximum_size=0
    for n in $(unique_values_desc "$@"); do
        local largest_at_this_level=$(printf '%s\n' "${histogram}" | \
            truncate_lines_to "${n}" | \
            largest_full_rect)
        if [ "${largest_at_this_level}" -gt "${maximum_size}" ]; then
            maximum_size=${largest_at_this_level}
        fi
    done
    printf '%s\n' "${maximum_size}"
}